### ISSUE TITLE
StatefulSet.spec is missing required field "serviceName"

### ISSUE THREAD

**Issue by greut** [viters/azurite-helm-chart#2]
Using 1.7.0 with client on 1.25.5 (and server on 1.24.4+k3s1)

> Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec 

Cheers,

**Comment by viters** [comment]
@greut 
Thanks for reporting. I will take it on tomorrow or day after tomorrow. If you would have fix ready by then, please send a PR.

**Comment by greut** [comment]
I did that quick fix, but it might be everything there is about it.

```patch
diff --git a/charts/azurite/templates/statefulset.yaml b/charts/azurite/templates/statefulset.yaml
index 3a5701b..a79acac 100644
--- a/charts/azurite/templates/statefulset.yaml
+++ b/charts/azurite/templates/statefulset.yaml
@@ -10,6 +10,7 @@ metadata:
     {{- toYaml . | nindent 4 }}
   {{- end }}
 spec:
+  serviceName: {{ $fullName }}
   replicas: {{ .Values.statefulset.replicaCount }}
   selector:
     matchLabels:
```

**Comment by viters** [comment]
@greut 
I've applied the change, although it will require to recreate the Azurite StatefulSet. `serviceName` is immutable.
