### ISSUE TITLE
Minikube | ImagePullBackoff Error

### ISSUE THREAD

**Issue by tqtrungse** [viters/azurite-helm-chart#3]
Hi, I copied and have used service.yaml and statefulset.yaml (only 2 these files and not modify) to deploy Azurite in Minikube, but I received _ImagePullBackoff_ error. Can I wrong something?

**Comment by viters** [comment]
@tqtrungse 
Could you show the exact yaml files that you are applying on minikube cluster?

**Comment by tqtrungse** [comment]
Thanks fro replying, here is my yaml files:

This is statefulset.yaml

`{{- $fullName := printf "%s" (include "azurite.fullname" . ) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "azurite.labels" . | nindent 4 }}
  {{- with .Values.statefulset.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.statefulset.replicaCount }}
  serviceName: {{ $fullName }}
  selector:
    matchLabels:
      app: {{ $fullName }}
  volumeClaimTemplates:
    - metadata:
        name: storage
        {{- if .Values.persistentVolume.annotations }}
        annotations:
          {{ toYaml .Values.persistentVolume.annotations | nindent 10 }}
        {{- end }}
      spec:
        {{- if .Values.persistentVolume.storageClass }}
        {{- if (eq "-" .Values.persistentVolume.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistentVolume.storageClass }}"
        {{- end }}
        {{- end }}
        accessModes:
          {{ toYaml .Values.persistentVolume.accessModes | nindent 10 }}
        resources:
          requests:
            storage: "{{ .Values.persistentVolume.size }}"
  template:
    metadata:
      {{- with .Values.statefulset.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $fullName }}
        {{- include "azurite.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: storage
          emptyDir: {}
      securityContext:
        {{- toYaml .Values.statefulset.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Chart.AppVersion | toString }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "azurite"
            - "-l"
            - "/data"
            - "--disableProductStyleUrl"
            - "--loose"
            {{- if .Values.config.blobs.enabled }}
            - "--blobHost"
            - "0.0.0.0"
            {{- end }}
            {{- if .Values.config.queues.enabled }}
            - "--queueHost"
            - "0.0.0.0"
            {{- end }}
            {{- if .Values.config.tables.enabled }}
            - "--tableHost"
            - "0.0.0.0"
            {{- end }}
          ports:
            {{- if .Values.config.blobs.enabled }}
            - containerPort: 10000
              name: blobs
            {{- end }}
            {{- if .Values.config.queues.enabled }}
            - containerPort: 10001
              name: queues
            {{- end }}
            {{- if .Values.config.tables.enabled }}
            - containerPort: 10002
              name: tables
            {{- end }}
          securityContext:
            {{- toYaml .Values.statefulset.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: storage
              mountPath: /data
          resources:
            {{- toYaml .Values.statefulset.resources | nindent 12 }}
      {{- with .Values.statefulset.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.statefulset.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.statefulset.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}`

This is service.yaml

`{{- $fullName := printf "%s" (include "azurite.fullname" . ) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    {{- include "azurite.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.config.blobs.enabled }}
    - port: 10000
      targetPort: blobs
      protocol: TCP
      name: blobs
    {{- end }}
    {{- if .Values.config.queues.enabled }}
    - port: 10001
      targetPort: queues
      protocol: TCP
      name: queues
    {{- end }}
    {{- if .Values.config.tables.enabled }}
    - port: 10002
      targetPort: tables
      protocol: TCP
      name: tables
    {{- end }}
  selector:
    app: {{ $fullName }}`

This is ingress.yaml

`{{- $fullName := printf "%s" (include "azurite.fullname" . ) -}}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    {{- include "azurite.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if and (.Values.config.blobs.enabled) (.Values.ingress.host.blobs) }}
    - host: {{ .Values.ingress.host.blobs | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: blobs
    {{- end }}
    {{- if and (.Values.config.queues.enabled) (.Values.ingress.host.queues) }}
    - host: {{ .Values.ingress.host.queues | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: queues
    {{- end }}
    {{- if and (.Values.config.tables.enabled) (.Values.ingress.host.tables) }}
    - host: {{ .Values.ingress.host.tables | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: tables
    {{- end }}
{{- end }}`

This is job.yaml

`{{- $fullName := printf "%s" (include "azurite.fullname" . ) -}}
{{- if .Values.config.blobs.initJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    {{- include "azurite.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      containers:
        - name: azurite-init-containers
          image: lukaszczesniak/azure-storage-init-containers
          env:
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1"
            - name: AZURE_STORAGE_PUBLIC_CONTAINERS
              value: {{ .Values.config.blobs.initJob.containers.public | default "" }}
            - name: AZURE_STORAGE_PRIVATE_CONTAINERS
              value: {{ .Values.config.blobs.initJob.containers.private | default "" }}
      restartPolicy: OnFailure
  backoffLimit: 10
{{- end }}`

This is values.yaml

`nameOverride: null

fullnameOverride: null

image:
  name: mcr.microsoft.com/azure-storage/azurite
  pullPolicy: Always
  pullSecrets: []

config:
  blobs:
    enabled: true
    ## https://github.com/viters/azure-storage-init-containers
    initJob:
      enabled: false
      containers:
        public: ""
        private: ""
  queues:
    enabled: true
  tables:
    enabled: true

statefulset:
  affinity: {}
  annotations: {}
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
    runAsGroup: 10000
    runAsUser: 10000
    fsGroup: 10000
  replicaCount: 1
  resources: {}
  tolerations: []
  containerSecurityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false

service:
  type: ClusterIP
  labels: {}
  annotations: {}

persistentVolume:
  enabled: true
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClass: null

ingress:
  enabled: false
  labels: {}
  annotations: {}
  host:
    blobs: null
    queues: null
    tables: null
  className: "public"
  tls: []`

**Comment by viters** [comment]
@tqtrungse 
I do not get it, are you trying to apply Helm files directly to Kubernetes, without Helm? 
Have you manually filled the templates with values? Just applying templates will not work.

Why are you not using Helm? You can download Helm chart and install it from local path, if you do not want to use GitHub's repo. [More on installing charts on Minikube](https://docs.bitnami.com/kubernetes/get-started-kubernetes/#step-4-install-and-configure-helm) and [the docs for Helm install](https://helm.sh/docs/helm/helm_install/).

**Comment by tqtrungse** [comment]
@viters 
I have used Helm from beginning. I know what I'm doing. I configed wrong version azurite. Anyway, I fixed my bug.
Thanks for supporting, I think you can closed this issue.

**Comment by viters** [comment]
@tqtrungse 
Sure thing, glad you've managed to work it out.
